placeholders:
    placeholders:
        scripts_after:
            items:
                window_bundle_js:
                    order: 200

    items:
       window_bundle_js:
            template: '@@OroWindows/Include/javascript.html.twig'
