knp_gaufrette:
    adapters:
        attachments:
            local:
                directory: '%kernel.project_dir%/var/%oro_attachment.filesystem_dir.attachments%'
        mediacache:
            local:
                directory: '%kernel.project_dir%/public/%oro_attachment.filesystem_dir.mediacache%'
        protected_mediacache:
            local:
                directory: '%kernel.project_dir%/var/%oro_attachment.filesystem_dir.protected_mediacache%'
    filesystems:
        attachments:
            adapter:    attachments
            alias:      attachments_filesystem
        mediacache:
            adapter:    mediacache
            alias:      mediacache_filesystem
        protected_mediacache:
            adapter:    protected_mediacache
            alias:      protected_mediacache_filesystem

    stream_wrapper: ~

oro_api:
    error_title_overrides:
        'file constraint from system config constraint': 'file constraint'

oro_security:
    login_target_path_excludes:
        - oro_attachment_get_file
        - oro_resize_attachment
        - oro_filtered_attachment
        - _oro_filtered_attachment
