oro_notification:
    resource:     "@OroNotificationBundle/Controller"
    type:         annotation
    prefix:       /notification


#
# DEPRECATED OLD REST API ROUTES
#

oro_api_options_emailnotications:
    path: '/api/rest/{version}/emailnotications.{_format}'
    methods: [OPTIONS]
    defaults:
        _controller: 'Oro\Bundle\NotificationBundle\Controller\Api\Rest\EmailNotificationController::optionsAction'
        _format: json
        version: latest
    requirements:
        _format: json
        version: latest|v1


#
# OLD REST API ROUTES
#

oro_api_delete_emailnotication:
    path: '/api/rest/{version}/emailnotications/{id}.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\NotificationBundle\Controller\Api\Rest\EmailNotificationController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json
        version: latest|v1
