oro_comment_bundle:
    resource:     "@OroCommentBundle/Controller"
    type:         annotation
    prefix:       /

#
# REST actions
#
oro_api_comment_get_items:
    path: api/rest/{version}/relation/{relationClass}/{relationId}/comment.{_format}
    defaults: { _controller: Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::cgetAction, _format: json, version: latest }
    methods: [GET]

oro_api_comment_create_item:
    path: api/rest/{version}/relation/{relationClass}/{relationId}/comment.{_format}
    defaults: { _controller: Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::postAction, _format: json, version: latest }
    methods: [POST]

oro_api_comment_get_item:
    path: api/rest/{version}/comment/{id}.{_format}
    defaults: { _controller: Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::getAction, _format: json, version: latest }
    methods: [GET]

oro_api_comment_update_item:
    path: api/rest/{version}/comment/{id}.{_format}
    defaults: { _controller: Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::putAction, _format: json, version: latest }
    methods: [POST]

oro_api_comment_remove_attachment_item:
    path: api/rest/{version}/comment/{id}/removeAttachment.{_format}
    defaults: { _controller: Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::removeAttachmentAction, _format: json, version: latest }
    methods: [POST]

oro_api_comment_delete_item:
    path: api/rest/{version}/comment/{id}.{_format}
    defaults: { _controller: Oro\Bundle\CommentBundle\Controller\Api\Rest\CommentController::deleteAction, _format: json, version: latest }
    methods: [DELETE]
