label: Oro Theme
logo: bundles/oroui/themes/oro/images/oro-platform-logo.svg
icon: bundles/oroui/themes/oro/images/favicon.ico
rtlSupport: false
styles:
    css:
        inputs:
            - bundles/oroui/themes/oro/css/style.css
        output: css/oro.css

