css:
    inputs:
        - 'bundles/oroform/css/scss/main.scss'


css_tinymce_content:
    inputs:
        - 'bundles/oroform/css/scss/tinymce/content.scss'
    output: css/tinymce/content.min.css

css_tinymce_wysiwyg_editor:
    inputs:
        - 'bundles/oroform/css/scss/tinymce/wysiwyg-editor.scss'
    output: css/tinymce/wysiwyg-editor.css
