oro_note_bundle:
    resource:     "@OroNoteBundle/Controller"
    type:         annotation
    prefix:       /

oro_note_bundle_api:
    resource: "@OroNoteBundle/Controller/Api/Rest/NoteController.php"
    type: rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest

#
# REST actions
#
oro_api_get_notes:
    path: api/rest/{version}/notes/{entityClass}/{entityId}.{_format}
    defaults: {_controller: Oro\Bundle\NoteBundle\Controller\Api\Rest\NoteController::cgetAction, _format: json}
    methods: [GET]

oro_api_get_note:
    path: api/rest/{version}/notes/{id}.{_format}
    defaults: {_controller: Oro\Bundle\NoteBundle\Controller\Api\Rest\NoteController::getAction, _format: json}
    methods: [GET]

oro_api_post_note:
    path: api/rest/{version}/notes.{_format}
    defaults: {_controller: Oro\Bundle\NoteBundle\Controller\Api\Rest\NoteController::postAction, _format: json}
    methods: [POST]
