oro_workflow_api:
    resource: "@OroWorkflowBundle/Controller/Api/Rest/WorkflowController.php"
    type:     rest

oro_workflow_definition_api:
    resource: "@OroWorkflowBundle/Controller/Api/Rest/WorkflowDefinitionController.php"
    type:     rest

oro_workflow_entity_api:
    resource: "@OroWorkflowBundle/Controller/Api/Rest/EntityController.php"
    type:     rest

oro_workflow_process_api:
    resource: "@OroWorkflowBundle/Controller/Api/Rest/ProcessController.php"
    type:     rest

# deprecated API routes
oro_workflow_api_rest_process_activate: # a copy of oro_api_process_activate
    path:            /api/rest/{version}/process/activate/{processDefinition}.{_format}
    methods:         [POST]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\ProcessController::activateAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1

oro_workflow_api_rest_process_deactivate: # a copy of oro_api_process_deactivate
    path:            /api/rest/{version}/process/deactivate/{processDefinition}.{_format}
    methods:         [POST]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\ProcessController::deactivateAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1

oro_workflow_api_rest_workflowdefinition_get: # a copy of oro_api_workflow_definition_get
    path:            /api/rest/{version}/workflowdefinition/{workflowDefinition}.{_format}
    methods:         [GET]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\WorkflowDefinitionController::getAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1

oro_workflow_api_rest_workflowdefinition_post: # a copy of oro_api_workflow_definition_post
    path:            /api/rest/{version}/workflowdefinition/{workflowDefinition}.{_format}
    methods:         [POST]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\WorkflowDefinitionController::postAction
        _format:     json
        version:     latest
        workflowDefinition: ~
    requirements:
        _format:     json
        version:     latest|v1

oro_workflow_api_rest_workflowdefinition_put: # a copy of oro_api_workflow_definition_put
    path:            /api/rest/{version}/workflowdefinition/{workflowDefinition}.{_format}
    methods:         [PUT]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\WorkflowDefinitionController::putAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1

oro_workflow_api_rest_workflowdefinition_delete: # a copy of oro_api_workflow_definition_delete
    path:            /api/rest/{version}/workflowdefinition/{workflowDefinition}.{_format}
    methods:         [DELETE]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\WorkflowDefinitionController::deleteAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1

oro_workflow_api_rest_entity_get: # a copy of oro_api_workflow_entity_get
    path:            /api/rest/{version}/workflowentity.{_format}
    methods:         [GET]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\EntityController::getAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1

oro_workflow_api_rest_workflow_get: # a copy of oro_api_workflow_get
    path:            /api/rest/{version}/workflow/{workflowItemId}.{_format}
    methods:         [GET]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\WorkflowController::getAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1
        workflowItemId: \d+

oro_workflow_api_rest_workflow_delete: # a copy of oro_api_workflow_delete
    path:            /api/rest/{version}/workflow/{workflowItemId}.{_format}
    methods:         [DELETE]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\WorkflowController::deleteAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1
        workflowItemId: \d+

oro_workflow_api_rest_workflow_activate: # a copy of oro_api_workflow_activate
    path:            /api/rest/{version}/workflow/activate/{workflowDefinition}.{_format}
    methods:         [POST]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\WorkflowController::activateAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1

oro_workflow_api_rest_workflow_deactivate: # a copy of oro_api_workflow_deactivate
    path:            /api/rest/{version}/workflow/deactivate/{workflowDefinition}.{_format}
    methods:         [POST]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\WorkflowController::deactivateAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1

oro_workflow_api_rest_workflow_start: # a copy of oro_api_workflow_start
    path:            /api/rest/{version}/workflow/start/{workflowName}/{transitionName}.{_format}
    methods:         [POST]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\WorkflowController::startAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1

oro_workflow_api_rest_workflow_transit: # a copy of oro_api_workflow_transit
    path:            /api/rest/{version}/workflow/transit/{workflowItemId}/{transitionName}.{_format}
    methods:         [POST]
    defaults:
        _controller: Oro\Bundle\WorkflowBundle\Controller\Api\Rest\WorkflowController::transitAction
        _format:     json
        version:     latest
    requirements:
        _format:     json
        version:     latest|v1
        workflowItemId: \d+
